import type { Metadata } from "next";
// Importe le type Metadata depuis la bibliothèque Next.js pour définir les métadonnées de la page.

import { Inter } from "next/font/google";
// Importe la police Inter depuis la bibliothèque Next.js pour être utilisée dans le CSS.

import "./globals.css";
// Importe le fichier CSS global "./globals.css", qui contient des styles appliqués à l'ensemble de l'application.

import Header from "../components/header";
// Importe le composant Header depuis le fichier "../components/header".

import Footer from "../components/footer";
// Importe le composant Footer depuis le fichier "../components/footer".

import Navigation from "../components/navigation";
// Importe le composant Navigation depuis le fichier "../components/navigation".

const inter = Inter({ subsets: ["latin"] });
// Déclare une constante inter qui contient la police Inter avec le sous-ensemble "latin".

// Définit les métadonnées de la page exportées sous la forme d'un objet de type Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Définit le composant RootLayout qui reçoit des enfants (children) comme propriété et retourne un élément JSX
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Définit la structure de base HTML avec la langue en anglais */}
      <body className={inter.className}>
        {/* Ajoute la classe CSS de la police Inter au corps du document */}
        <Header />
        {/* Affiche le composant Header */}
        <Navigation />
        {/* Affiche le composant Navigation */}
        {children}
        {/* Affiche les enfants passés en tant que propriété du composant RootLayout */}
        <Footer />
        {/* Affiche le composant Footer */}
      </body>
    </html>
  );
}
